<a href="https://colab.research.google.com/github/nasira-banu/nasirabanussprojectiiith/blob/main/Basics_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Basics of Linear Algebra

Import the NumPy library for Linear Algebra functions and Matplotlib for some plotting functions.

In [59]:
import numpy as np #numpy is used for linear algebra
import matplotlib.pyplot as plt #pyplot from matplotlib

### Transpose of Matrix

Matrix transpose is performed with the transpose method on a nested list or a Python array, or a higher-dimensional Numpy array.

In [60]:
 # Transpose of a Matrix (as nested list)
 a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
 at = np.transpose(a)
 print('a\n',a)
 print('b\n',at)

a
 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
b
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


If the matrix is a NumPy array, it can be treated as an object and method T can be applied over it as follows.

In [61]:
  # Transpose of a Matrix (as NumPy array)
print ("Matrix and its Transpose") #donot use nested list, use an np array instead
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a.T
print('a\n',a)
print('b\n',b)

Matrix and its Transpose
a
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


The dot method of NumPy performs dot-matrix product (scalar product) for 1D or higher dimensional arrays. If the inputs are scalars (numbers), it performs multiplication.

In [62]:
 # scalars
 a = 15
 b = 3
 z = np.dot(a,b)
 print(z)

45


In [63]:
 z = a * b
 print(z)

45


In the case of one- or higher-dimensional arrays, the inputs can be either NumPy arrays, Python arrays, Python lists or Python’s nested lists.

In [64]:
 # 1D arrays or vectors
 arr1 = np.array([12,30,6])
 arr2 = np.array([15,3,3])
 z = np.dot(arr1,arr2)
 print(z)


288


In [65]:
 # 2D arrays or matrices
 #np.dot is matrix multiplication and indices matter columns of first matrix == row of the second matrix
 #np.array takes only one argument
 arr1 = np.array([[1,15,4],[9,18,12],[12,3,4]])
 arr2 = np.array([[7,8,6],[4,21,6],[8,7,12]])
 z1 = np.matmul(arr1,arr2)
 z = np.dot(arr1,arr2)
 print(z1)
 print(z)
print(z==z1) #same result

[[ 99 351 144]
 [231 534 306]
 [128 187 138]]
[[ 99 351 144]
 [231 534 306]
 [128 187 138]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


We can obtained the same result using `np.matmul()`.

### Numpy Arrays
A NumPy array is a Numpy object upon which the dot method can be performed as below. However, this method accepts only NumPy arrays to operate on.


In [66]:
 # convert lists into NumPy arrays
 newa = np.array(arr1)
 newb = np.array(arr2)
 z = newa.dot(newb)
 print(z)

[[ 99 351 144]
 [231 534 306]
 [128 187 138]]


### The multi_dot method

It performs dot (scalar) product with 2 or more input matrices. First and last arrays can be either 1D or 2D arrays. However, the dimensions of the matrices must suit subsequent scalar matrix multiplication.

In [67]:
 # matrices with random integers: entries ranging from -4 to 4
 a = np.random.randint(-12,12,(400,3))
 b = np.random.randint(-4,4,(3,400))
 c = np.random.randint(-10,10,(400,400))


 # Perform multiple matrix multiplication
 z = np.linalg.multi_dot([a,b,c])

The result of this method can be obtained with successive dot products of matrices but multi_dot functions in an optimized manner. It decides the order of dot multiplication to complete the entire process efficiently.

In [68]:
#matrix dimension obtained
 s = z.shape
 print(s)

IndentationError: unexpected indent (<ipython-input-68-9616cf26e438>, line 2)

In [ ]:
 %%time
 z = a.dot(b).dot(c)
 print(z, '\n')
s = z.shape
print(s) #similar reslut

#### Observe the CPU time that multi_dot consumes as against CPU time that successive dot methods consume to arrive at the same solution. Which one is more efficient, why ?

### Inner Product

The inner product is the scalar multiplication of one vector (or matrix) and the transpose of another vector (or matrix). If both arrays are 1D arrays, their dimensions should be identical. If either or both arrays are higher-dimensional, then the last dimensions of both arrays should be identical.

In [ ]:
 a = np.array([[19,9,3,4], [4,-1,7,9]])
 b = np.array([6,3,2,9])
 z = np.inner(a,b)
 z1 = a.dot(b.T)
 print(z)
 print(z1)   #same results

### Outer Product

Outer product is the dot product of a column vector of size Mx1 and a row vector of size 1xN. The resulting array is a matrix of size MxN.


In [ ]:
 arr1 = np.array([11,12,13,14,15,19,23])
 arr2 = np.array([6,3,2]) #multiplocation of a row and column vector
 z = np.outer(arr1,arr2)
 print(z)

The last dimension of the second array and the second-to-last dimension of the first array should be identical to perform matrix multiplication. Further, the symbol @ is also used to perform matrix multiplication.

In [ ]:
 # Here, 'a' matrix is 3D, which means there are 3 matrices each of 2x5 size
 # Similarly, for 'b' matrix
 # So we perform 3 matrix multiplication operations each with "2*4" and "4*6" matrices from a and b
 arr1 = np.random.randint(1,5,[2,4])
 arr2 = np.random.randint(1,10,[4,6])
 z = arr1 @ arr2
 print(z)
 print(z.shape)

### Matrix Determinant

Matrix determinant can be calculated using the method det available in the linalg module.

In [ ]:
 # generate a random integer matrix of size 3 by 3
 a = np.random.randint(1,10,[3,3])
 det = np.linalg.det(a)
 print(int(det))

### Matrix Inverse

Inverse of a square matrix can be derived using the inv method of the linalg module.


In [ ]:
 a = np.random.randint(1,10,[4,4])
 inv = np.linalg.inv(a)
 print(a)
 print()
 print(inv)


### Matrix Power

Matrix Power is a general method to obtain either positive or negative powers of a given square matrix. The first negative power of a matrix is technically termed its inverse. Thus, the matrix_power method can be used to find the inverse or any power of a matrix.

In [ ]:
 a = np.random.randint(1,10,[3,3])
 # positive powers of matrix
 a_2 = np.linalg.matrix_power(a, 2)
 a_10 = np.linalg.matrix_power(a,10)
 # inverse of matrix #inverse is basically power of -1
 a_inv_1 = np.linalg.matrix_power(a, -1)
 a_inv_4 = np.linalg.matrix_power(a, -4)
 print('matrix \n', a)
 print('\n matrix to the power 2\n', a_2)
 print('\n matrix to the power 10\n', a_10)
 print('\n matrix inverse \n', a_inv_1)
 print('\n matrix quad inverse \n', a_inv_4)

### Eigenvalues and Eigenvectors

Eigenvalues and Eigenvectors of a matrix can be determined as follows. If Eigen values cannot be determined, the method throws an error (Eg. Singular matrix).

In [ ]:
arr = np.random.randint(1,10,[3,3])
eig_value, eig_vector = np.linalg.eig(arr)  #.eig is used to get eigen values and rigen vectors
eig_value1 = np.linalg.eigvals(arr)
print('Eigenvalues using .eig are: \n', eig_value)
print('Eigenvalues using .eigvals are: \n', eig_value1)
print(eig_value==eig_value1)
print('\nEigenvectors are: \n', eig_vector)


### Traces of a Matrix

Traces of a square matrix is the summation of its diagonal elements.

In [ ]:
a = np.eye(10) #identity matrix
print(a)
z = np.trace(a)
print('\nTrace of matrix is: ',z)

### Matrix Norm

Matrix or vector norm is calculated using the norm method of the linalg module.


In [ ]:
a = np.arange(12).reshape(4,3)
z = np.linalg.norm(a)
print(a)
print('\n Frobenius Norm of above matrix:')
print(z)


#### Norm of Matrix

Axis-wise norm determination is also possible by specifying the axis as an integer.


In [ ]:
# Norm along axis 0
arr1 = np.arange(20).reshape(4,5)
z = np.linalg.norm(a, axis=1) #along column
print(z)

### Solving System of Equations

When we think of Linear Algebra, the system of linear equations comes to our mind first, as it is tedious, time-consuming and error-prone. NumPy solves systems of linear equations in a fraction of seconds!

In [ ]:
# Coefficient Matrix obtained using Guassian elimination
a = np.random.randint(1,20,[5,5])
# Dependent variable vector
b = np.array([7,8,9,12,11])
# solution a*x = b
x = np.linalg.solve(a,b)
print('A=')
print(a)
print('\n B = ')
print(b)
print('\nX =')
print(x)

In [ ]:
# Check for correctness
B = a.dot(x)
print(B)

# This ‘B’ array is identical to the input ‘b’ array. Hence, our solution is correct.

### Singular Value Decomposition

Singular Value Decomposition (SVD) is one of the great dimension-reduction algorithms in machine learning. It identifies the principal components and arranges them by rank. The top ranked components contribute greatly to the original array. Here, we explore SVD with an image to get better understanding.
Widely used for image processing

In [ ]:
from skimage import data
# download a sample image
image = data.astronaut()
print(image.dtype, image.min(), image.max(), image.shape)
plt.imshow(image) #matplotlib for visualisation
plt.show()

In [ ]:
# Normalize the image by dividing it by the maximum value, 255 and reorder the axes to be (3,400,600).

# normalize image
img = image/255.0
# reorder the axes to have colour channels as the first dimension
img = np.transpose(img, axes=(2,0,1))

Perform SVD on the image. It decomposes the original image into three components: U matrix, Sigma vector, and V matrix. The Sigma vector is the diagonal entries of the Sigma matrix. Hence, it is advisable that the Sigma vector may be reformed into a diagonal matrix. It should be noted that the first dimension 3 refers to the three colour channels.

In [ ]:
U,S,V = np.linalg.svd(img)
print(U.shape, S.shape, V.shape)


In [ ]:
# S matrix should have dimensions suitable for matrix multiplication
Sigma = np.zeros((3,512,512))
for i in range(3):
  np.fill_diagonal(Sigma[i,:,:], S[i,:])
print(Sigma.shape)

In [ ]:
# Reconstruct the original image without any dimension reduction.
reconst = U @ Sigma @ V
reconst = np.transpose(reconst, axes=(1,2,0))
plt.imshow(reconst)
plt.show()


In [69]:
# NumPy SVD reconstruction

# Reconstruct the data by reducing the common dimensions from 512 to 50.

k = 50
reconst = U @ Sigma[:,:,:k] @ V[:,:k,:]
reconst = np.transpose(reconst, axes=(1,2,0))
plt.imshow(reconst)
plt.show()

NameError: name 'U' is not defined

#### Dimensionality reduction

It is amazing that we reconstructed the image with most details, even at a reduction of ¼.

We can once again reconstruct the same image by reducing the data points from 512 to 20.


In [ ]:
k = 20
reconst = U @ Sigma[:,:,:k] @ V[:,:k,:]
reconst = np.transpose(reconst, axes=(1,2,0))
plt.imshow(reconst)
plt.show()

#### SVD reconstruction

Out of 400 data points, merely 20 data points can reconstruct the image with key feature details! This is why the old mathematical algorithm- SVD is still popular in machine learning.

### Additional References

[Numpy Matrix Multiplication Terminology](https://likegeeks.com/numpy-matrix-multiplication/#Basic_Terminologies)